syntax = "proto3";

package storage.v1;

option go_package = "github.com/zarielnd/file-management-service-go/gen/storage/v1;storagev1";

import "google/protobuf/timestamp.proto";

service StorageService {
  rpc UploadFile(stream UploadFileRequest) returns (UploadFileResponse);
  rpc GetFile(GetFileRequest) returns (stream GetFileResponse);
  rpc GetMetadata(GetMetadataRequest) returns (FileMetadata);
  rpc ListFiles(ListFilesRequest) returns (ListFilesResponse);
  rpc DownloadArchive(DownloadArchiveRequest) returns (stream DownloadArchiveResponse);
}

message UploadFileRequest {
  oneof payload {
    FileInfo info = 1;
    bytes chunk_data = 2;
  }
}

message FileInfo {
  string filename = 1;
  string content_type = 2;
  int64 size = 3;
}

message UploadFileResponse {
  FileMetadata file = 1;
}

message GetFileRequest {
  string id = 1;
}

message GetFileResponse {
  FileMetadata metadata = 1; // only in first message
  bytes data = 2;
}

message GetMetadataRequest {
  string id = 1;
}

message FileMetadata {
  string id = 1;
  string name = 2;
  int64 size = 3;
  string content_type = 4;
  string checksum = 5;
  google.protobuf.Timestamp created_at = 6;
}

message ListFilesRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message ListFilesResponse {
  repeated FileMetadata files = 1;
  int32 total = 2;
}

message DownloadArchiveRequest {
  repeated string file_ids = 1;
}

message DownloadArchiveResponse {
  bytes data = 1;
}