FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /bin/http-server ./cmd/server


FROM alpine:3.22

WORKDIR /app

COPY --from=builder /bin/http-server .

EXPOSE 8080

CMD ["./http-server"]