// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=../mocks/client_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	client "github.com/zarielnd/file-management-service-go/services/file-server/internal/client"
	domain "github.com/zarielnd/file-management-service-go/services/file-server/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageClient is a mock of StorageClient interface.
type MockStorageClient struct {
	ctrl     *gomock.Controller
	recorder *MockStorageClientMockRecorder
	isgomock struct{}
}

// MockStorageClientMockRecorder is the mock recorder for MockStorageClient.
type MockStorageClientMockRecorder struct {
	mock *MockStorageClient
}

// NewMockStorageClient creates a new mock instance.
func NewMockStorageClient(ctrl *gomock.Controller) *MockStorageClient {
	mock := &MockStorageClient{ctrl: ctrl}
	mock.recorder = &MockStorageClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageClient) EXPECT() *MockStorageClientMockRecorder {
	return m.recorder
}

// DownloadArchive mocks base method.
func (m *MockStorageClient) DownloadArchive(ctx context.Context, ids []string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadArchive", ctx, ids)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadArchive indicates an expected call of DownloadArchive.
func (mr *MockStorageClientMockRecorder) DownloadArchive(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadArchive", reflect.TypeOf((*MockStorageClient)(nil).DownloadArchive), ctx, ids)
}

// Fetch mocks base method.
func (m *MockStorageClient) Fetch(ctx context.Context, id string) (io.ReadCloser, domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, id)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(domain.File)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Fetch indicates an expected call of Fetch.
func (mr *MockStorageClientMockRecorder) Fetch(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockStorageClient)(nil).Fetch), ctx, id)
}

// GetDownloadURLs mocks base method.
func (m *MockStorageClient) GetDownloadURLs(ctx context.Context, ids []string) ([]client.DownloadURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadURLs", ctx, ids)
	ret0, _ := ret[0].([]client.DownloadURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDownloadURLs indicates an expected call of GetDownloadURLs.
func (mr *MockStorageClientMockRecorder) GetDownloadURLs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadURLs", reflect.TypeOf((*MockStorageClient)(nil).GetDownloadURLs), ctx, ids)
}

// GetUploadURL mocks base method.
func (m *MockStorageClient) GetUploadURL(ctx context.Context, filename, contentType string) (client.UploadURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUploadURL", ctx, filename, contentType)
	ret0, _ := ret[0].(client.UploadURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUploadURL indicates an expected call of GetUploadURL.
func (mr *MockStorageClientMockRecorder) GetUploadURL(ctx, filename, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUploadURL", reflect.TypeOf((*MockStorageClient)(nil).GetUploadURL), ctx, filename, contentType)
}

// List mocks base method.
func (m *MockStorageClient) List(ctx context.Context, page, pageSize int) ([]domain.File, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, pageSize)
	ret0, _ := ret[0].([]domain.File)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockStorageClientMockRecorder) List(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStorageClient)(nil).List), ctx, page, pageSize)
}

// Metadata mocks base method.
func (m *MockStorageClient) Metadata(ctx context.Context, id string) (domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata", ctx, id)
	ret0, _ := ret[0].(domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Metadata indicates an expected call of Metadata.
func (mr *MockStorageClientMockRecorder) Metadata(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockStorageClient)(nil).Metadata), ctx, id)
}

// Store mocks base method.
func (m *MockStorageClient) Store(ctx context.Context, input client.UploadInput) (domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, input)
	ret0, _ := ret[0].(domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockStorageClientMockRecorder) Store(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockStorageClient)(nil).Store), ctx, input)
}
