// Code generated by MockGen. DO NOT EDIT.
// Source: file.go
//
// Generated by this command:
//
//	mockgen -source=file.go -destination=../../mocks/file_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	client "github.com/zarielnd/file-management-service-go/services/file-server/internal/client"
	domain "github.com/zarielnd/file-management-service-go/services/file-server/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFileService is a mock of FileService interface.
type MockFileService struct {
	ctrl     *gomock.Controller
	recorder *MockFileServiceMockRecorder
	isgomock struct{}
}

// MockFileServiceMockRecorder is the mock recorder for MockFileService.
type MockFileServiceMockRecorder struct {
	mock *MockFileService
}

// NewMockFileService creates a new mock instance.
func NewMockFileService(ctrl *gomock.Controller) *MockFileService {
	mock := &MockFileService{ctrl: ctrl}
	mock.recorder = &MockFileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileService) EXPECT() *MockFileServiceMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockFileService) Download(ctx context.Context, id string) (io.ReadCloser, domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, id)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(domain.File)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Download indicates an expected call of Download.
func (mr *MockFileServiceMockRecorder) Download(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockFileService)(nil).Download), ctx, id)
}

// DownloadMultiple mocks base method.
func (m *MockFileService) DownloadMultiple(ctx context.Context, ids []string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadMultiple", ctx, ids)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadMultiple indicates an expected call of DownloadMultiple.
func (mr *MockFileServiceMockRecorder) DownloadMultiple(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadMultiple", reflect.TypeOf((*MockFileService)(nil).DownloadMultiple), ctx, ids)
}

// List mocks base method.
func (m *MockFileService) List(ctx context.Context, page, pageSize int) ([]domain.File, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, pageSize)
	ret0, _ := ret[0].([]domain.File)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockFileServiceMockRecorder) List(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFileService)(nil).List), ctx, page, pageSize)
}

// Metadata mocks base method.
func (m *MockFileService) Metadata(ctx context.Context, id string) (domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata", ctx, id)
	ret0, _ := ret[0].(domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Metadata indicates an expected call of Metadata.
func (mr *MockFileServiceMockRecorder) Metadata(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockFileService)(nil).Metadata), ctx, id)
}

// StartArchiveWorkflow mocks base method.
func (m *MockFileService) StartArchiveWorkflow(ctx context.Context, ids []string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartArchiveWorkflow", ctx, ids)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StartArchiveWorkflow indicates an expected call of StartArchiveWorkflow.
func (mr *MockFileServiceMockRecorder) StartArchiveWorkflow(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartArchiveWorkflow", reflect.TypeOf((*MockFileService)(nil).StartArchiveWorkflow), ctx, ids)
}

// Upload mocks base method.
func (m *MockFileService) Upload(ctx context.Context, input client.UploadInput) (domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, input)
	ret0, _ := ret[0].(domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockFileServiceMockRecorder) Upload(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFileService)(nil).Upload), ctx, input)
}
